# Generated by Django 3.1.7 on 2021-02-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='unity',
            field=models.CharField(choices=[('n', 'Quantity'), ('Gbps', 'Gigabits/s'), ('Kbps', 'Kilobits/s'), ('Mbps', 'Megabits/s'), ('GB', 'GigaBytes'), ('MB', 'MegaBytes'), ('KB', 'KiloBytes'), ('GHz', 'GHz')], help_text='Choose the measurement unit for the resource', max_length=10),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='unity',
            field=models.CharField(choices=[('n', 'Quantity'), ('Gbps', 'Gigabits/s'), ('Kbps', 'Kilobits/s'), ('Mbps', 'Megabits/s'), ('GB', 'GigaBytes'), ('MB', 'MegaBytes'), ('KB', 'KiloBytes'), ('GHz', 'GHz')], help_text='Choose the measurement unit for the resource', max_length=10),
        ),
    ]
