# Generated by Django 3.1.7 on 2021-02-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstalledDrivers',
            new_name='InstalledDriver',
        ),
    ]
