# Generated by Django 3.1.7 on 2021-02-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0002_auto_20210226_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='unity',
            new_name='unit',
        ),
    ]
