# Generated by Django 3.1.7 on 2021-02-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0003_auto_20210226_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='max_speed',
            field=models.FloatField(help_text='Insert the max speed of the link'),
        ),
    ]
