# Generated by Django 3.1.7 on 2021-03-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0004_auto_20210226_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='unity',
        ),
        migrations.AddField(
            model_name='driver',
            name='package',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='installeddriver',
            name='port',
            field=models.PositiveIntegerField(default=5555),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='unit',
            field=models.CharField(choices=[('Version', 'Version of Installed Software'), ('n', 'Quantity'), ('Mbps', 'Megabits/s'), ('KB', 'KiloBytes'), ('GHz', 'GHz')], default='', help_text='Choose the measurement unit for the resource', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='unit',
            field=models.CharField(choices=[('', 'Installed Software'), ('n', 'Quantity'), ('Gbps', 'Gigabits/s'), ('Kbps', 'Kilobits/s'), ('Mbps', 'Megabits/s'), ('GB', 'GigaBytes'), ('MB', 'MegaBytes'), ('KB', 'KiloBytes'), ('GHz', 'GHz')], help_text='Choose the measurement unit for the resource', max_length=10),
        ),
    ]
