# Generated by Django 3.1.7 on 2021-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0005_auto_20210313_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='unit',
            field=models.CharField(choices=[('Version', 'Version of Installed Software'), ('n', 'Quantity'), ('Kbps', 'Kilobits/s'), ('KB', 'KiloBytes'), ('GHz', 'GHz')], help_text='Choose the measurement unit for the resource', max_length=10),
        ),
    ]
