# Generated by Django 3.1.7 on 2021-03-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0007_auto_20210318_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure_handler.programmabletechnology'),
        ),
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('programmable_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_environments', to='infrastructure_handler.programmabletechnology')),
                ('requirements', models.ManyToManyField(blank=True, to='infrastructure_handler.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='execution_environments',
            field=models.ManyToManyField(to='infrastructure_handler.ExecutionEnvironment', verbose_name='Available execution environments'),
        ),
        migrations.AddField(
            model_name='driver',
            name='execution_environments',
            field=models.ManyToManyField(to='infrastructure_handler.ExecutionEnvironment'),
        ),
    ]
