# Generated by Django 3.1.7 on 2021-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0008_auto_20210318_1712'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('name', 'value'), name='unique_name_value_combination'),
        ),
    ]
