# Generated by Django 3.1.7 on 2021-03-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure_handler', '0006_auto_20210317_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('public_key', models.FileField(upload_to='nacr_keys/')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkServicePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_flag', models.CharField(choices=[('I', 'Ingress'), ('E', 'Egress'), ('B', 'Border'), ('C', 'Custom'), ('A', 'All')], max_length=1)),
                ('file_path', models.FilePathField()),
                ('hash', models.CharField(max_length=100)),
                ('nacr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_services', to='netapp_manager.repository')),
                ('network_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='netapp_manager.networkservice', verbose_name='Network Service')),
                ('requirements', models.ManyToManyField(to='infrastructure_handler.Resource')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_handler.programmabletechnology')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('command', models.TextField()),
                ('native_procedure', models.BooleanField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='netapp_manager.networkservicepackage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='networkservicepackage',
            constraint=models.UniqueConstraint(fields=('network_service', 'technology'), name='single_package_per_technology'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('name', 'package'), name='unique_action_name_per_package'),
        ),
    ]
