# Generated by Django 3.1.7 on 2021-04-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0002_auto_20210407_2208'),
        ('netapp_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkservicepackage',
            name='execution_environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_handler.executionenvironment'),
        ),
    ]
