# Generated by Django 3.1.7 on 2021-04-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0004_executionenvironment_version'),
        ('netapp_manager', '0002_auto_20210430_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkServicePackage',
            new_name='NetAppPackage',
        ),
    ]
