# Generated by Django 3.1.7 on 2021-04-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp_manager', '0002_networkservicepackage_execution_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='networkservice',
            name='categories',
            field=models.ManyToManyField(related_name='network_services', to='netapp_manager.Category'),
        ),
    ]
