# Generated by Django 3.1.7 on 2021-04-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp_manager', '0003_auto_20210430_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netapp',
            name='conflicts',
            field=models.ManyToManyField(blank=True, related_name='_netapp_conflicts_+', to='netapp_manager.NetApp'),
        ),
    ]
