# Generated by Django 3.1.7 on 2021-03-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp_manager', '0003_auto_20210317_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkservicepackage',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
    ]
