# Generated by Django 3.1.7 on 2021-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp_manager', '0003_auto_20210410_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkservicepackage',
            name='technology',
        ),
        migrations.AddField(
            model_name='networkservice',
            name='conflicts',
            field=models.ManyToManyField(related_name='_networkservice_conflicts_+', to='netapp_manager.NetworkService'),
        ),
    ]
