# Generated by Django 3.1.7 on 2021-03-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0006_auto_20210317_1825'),
        ('netapp_manager', '0004_auto_20210317_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkservicepackage',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='infrastructure_handler.Resource'),
        ),
    ]
