# Generated by Django 3.1.7 on 2021-03-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp_manager', '0005_auto_20210317_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='public_key',
            field=models.FileField(blank=True, null=True, upload_to='nacr_keys/'),
        ),
    ]
