# Generated by Django 3.1.7 on 2021-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp_manager', '0008_auto_20210318_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkservicepackage',
            name='type',
            field=models.CharField(choices=[('NetApp', 'NetApp'), ('VNA', 'VNA')], default='NetApp', max_length=6),
        ),
    ]
