# Generated by Django 3.1.7 on 2021-03-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_handler', '0008_auto_20210318_1712'),
        ('netapp_manager', '0009_networkservicepackage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkservicepackage',
            name='execution_environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_handler.executionenvironment'),
        ),
    ]
